version: '3'
services:
  app:
    container_name: app
    depends_on:
      - redis
    expose:
      - "5000"    
  redis:
    image: "redis:4.0-alpine"
    container_name: app-redis
    expose:
        - "6379"
