version: '2'
services:
  app:
    image: "111111.dkr.ecr.us-east-1.amazonaws.com/curiosityio/api:beta-$BETA_API_VERSION"
    user: node
    command: npm run production:run
    restart: always
    environment:
      - NODE_ENV=beta
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/111/111/111
      - SLACK_CHANNEL=name-here-channel
      - API_MAILGUN_API_KEY=key-111111
      - EMAIL_FROM_DOMAIN=noreply.example.com
      - EMAIL_FROM_NAME=No Reply
      - EMAIL_FROM_EMAIL_ADDRESS=noreply@example.com
      - VIRTUAL_HOST=beta.example.com
      - LETSENCRYPT_HOST=beta.example.com
      - LETSENCRYPT_EMAIL=you@example.com
      - VIRTUAL_PORT=5000
  redis:
    restart: always
    volumes:
      - /etc/docker/redis-storage/app/:/usr/local/var/db/redis/

networks:
  default:
    external:
      name: nginx-proxy-network
