version: '3.7'
services:
  app:
    image: "$DOCKER_IMAGE_NAME"
    user: node
    command: npm run _production
    restart: unless-stopped
    env_file:
      - ../../.env.staging
    networks:
      - external      
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:domainname.ofapp.com"
      - "traefik.port=5000"

  redis:
    restart: unless-stopped
    networks:
      - external
    volumes:
      - /etc/docker/redis-storage/app/:/usr/local/var/db/redis/

networks:
  external:
    external: true