version: '3.7'
services:
  app:
    image: "111111.dkr.ecr.us-east-1.amazonaws.com/curiosityio/api:staging-$API_VERSION"
    user: node
    command: npm run _production
    restart: unless-stopped
    env_file:
      - ../../.env.staging

  redis:
    restart: unless-stopped
    volumes:
      - /etc/docker/redis-storage/app/:/usr/local/var/db/redis/

networks:
  default:
    external:
      name: nginx-proxy-network
