version: '2'
services:
  app:
    container_name: app
    mem_limit: 250000000 # Nodejs best practice to limit memory on applications.
    memswap_limit: 500000000
    depends_on:
      - redis
    expose:
      - "5000"
    environment:
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/fake
      - SLACK_CHANNEL=fake
      - API_MAILGUN_API_KEY=key-fake
      - EMAIL_FROM_DOMAIN=example.com
      - EMAIL_FROM_NAME=Joe Boe
      - EMAIL_FROM_EMAIL_ADDRESS=joe@example.com
      - ADMIN_AUTH_PASSWORD=12345
      - ADMIN_AUTH_TOKEN=12345
  redis:
    image: "redis:4.0-alpine"
    container_name: app-redis
    expose:
        - "6379"
