version: '3.7'
services:  
  dev-db:
    image: "postgres:9.6-alpine"
    container_name: dev-db
    ports:
      - "5432:5432"
    env_file:
      - ../../.env.development
  redis:
    image: "redis:4.0-alpine"
    container_name: app-redis
    ports:
      - "6379:6379"