# default is development/testing
default:
  secrets:
    - ".env"

sets:
  common: 
    secrets:
      - "app/config/firebase_key.json"
      - "app/config/firebase_projects.json"
  production:
  testing:
  development: