# default is development/testing
default:
  secrets:
    - "app/.env"

sets:
  common: 
    secrets:
      - "app/config/projects.json"
      - "ansible/group_vars/dbservers/production.yml"
      - "ansible/group_vars/dbservers/testing.yml"
  production:
  testing: