language: node_js
services:
  - docker

env:
  global:        
    - FOO=bar
install:  
  - gem install cici
  - cici decrypt --verbose # for development/testing  

cache:
  bundler: true
  npm: true 

jobs:
  include:
    - stage: commit
      script: 
        - set -e 
        - npx install-subset install test
        - npm run test
    - stage: pr
      script:
        - set -e
        - npx install-subset install test
        - npm run test
    # - stage: deploy
    #   script:         
    #     - ruby ./bin/ci/docker.rb deploy 

stages:
  - name: commit 
    if: type IN (push) AND tag IS blank
  - name: pr
    if: type IN (pull_request)
  - name: deploy
    if: tag IS present
