language: node_js
services:
  - docker

before_install:
  - gem install cici

before_script:
  - cici decrypt --verbose # for development/testing  

cache:
  npm: true 

env:
  global:
    - DOCKER_REGISTRY=ghcr.io # github registry
    - DOCKER_USERNAME=username-here
    # --------- The below entries need to be created as secrets -------------
    # DOCKER_PASSWORD - GitHub token you generated to give access to packages. 
    # GITHUB_TOKEN - personal access token where github username has push access to the repo to make comments and releases. 
    # CODECOV_TOKEN - codecov.io token for repository. Used for test coverage.
    # HONEY_BADGER_API_KEY - API key to honeybadger project. Used to upload source maps.

jobs:
  include:
    - stage: lint
      script: 
        - set -e 
        - npm i @commitlint/travis-cli @commitlint/config-conventional && npx commitlint-travis
    - stage: tests
      script:
        - set -e
        - npx install-subset install test
        - npm run test && npx codecov
    - stage: testing-deploy
      script:         
        - set -e
        - export DEPLOY_ENV=testing
        - export MAKE_RELEASE=true
        - export K8S_NAMESPACE=app-testing
        - cici decrypt --set $DEPLOY_ENV
        - ./bin/deploy.sh
    - stage: prod-deploy
      script:         
        - set -e
        - export DEPLOY_ENV=production
        - export MAKE_RELEASE=false
        - export K8S_NAMESPACE=app-production
        - cici decrypt --set $DEPLOY_ENV
        - ./bin/deploy.sh

stages:
  - name: tests
    if: type IN (push, pull_request) AND tag IS blank    
  - name: lint
    if: type IN (push, pull_request) AND tag IS blank    
  - name: testing-deploy
    if: type IN (push) AND branch IN (master, beta)
  - name: prod-deploy
    if: type IN (push) AND branch = production-deploy
