language: node_js
services:
  - docker

env:
  global:        
    - DOCKER_COMPOSE_VERSION=1.24.1
    - STAGING_DEPLOY_USER=core
    - STAGING_DEPLOY_HOST=111.111.111.111
    - PROD_DEPLOY_USER=core
    - PROD_DEPLOY_HOST=222.222.222.222    
    - DEPLOY_SSH_PORT=22
    # ------------ SECRETS ------------
    # DANGER_GITHUB_API_TOKEN
before_install:
  - curl -o- https://raw.githubusercontent.com/levibostian/ci-bootstrap/master/docker/compose-install.sh | bash     
install:  
  - bundle install
  - bundle exec cici decrypt --verbose # for development/testing  

cache:
  bundler: true
  npm: true 

jobs:
  include:
    - stage: commit
      script: 
        - set -e 
        - npx install-subset install test
        - npm run test:setup
        - npm run test
    - stage: pr
      script:
        - set -e
        - npx install-subset install test
        - npm run test:setup
        - npm run test
    # - stage: deploy
    #   script:         
    #     - ruby ./bin/ci/docker.rb deploy 

stages:
  - name: commit 
    if: type IN (push) AND tag IS blank
  - name: pr
    if: type IN (pull_request)
  - name: deploy
    if: tag IS present
