language: node_js
services:
  - docker

env:
  global:        
    - DOCKER_COMPOSE_VERSION=1.24.1
    - STAGING_DEPLOY_USER=core
    - STAGING_DEPLOY_HOST=111.111.111.111
    - PROD_DEPLOY_USER=core
    - PROD_DEPLOY_HOST=222.222.222.222    
    - DEPLOY_SSH_PORT=22
    # ------------ SECRETS ------------
    # DANGER_GITHUB_API_TOKEN
before_install:
  - curl -o- https://raw.githubusercontent.com/levibostian/ci-bootstrap/master/docker/compose-install.sh | bash   
  - cp .env.example .env # for development 
install:
  - npm install
  - bundle install
  - curl https://raw.githubusercontent.com/madcoda/dotenv-shell/master/dotenv.sh > ~/dotenv; chmod +x ~/dotenv;
  - ruby bin/secrets.rb decrypt 

cache:
  bundler: true
  npm: true 

jobs:
  include:
    - stage: commit
      script: 
        - rm .env; cp secrets/testing/.env .env; npm run test:setup; npm run test;
        - ruby ./bin/ci/docker.rb test
    - stage: pr
      script:
        - rm .env; cp secrets/testing/.env .env; npm run test:setup; npm run test;
        - bundle exec danger --fail-on-errors=true
    - stage: deploy
      script: 
        - ruby ./bin/ci/docker.rb deploy 

stages:
  - name: commit 
    if: type IN (push) AND tag IS blank
  - name: pr
    if: type IN (pull_request)
  - name: deploy
    if: tag IS present
