version: '2'
services:
  foo-app:
    image: "1234567890.dkr.ecr.us-east-1.amazonaws.com/levibostian/foo"
    user: app
    command: npm run run-build
    restart: always
    volumes:
      - /etc/docker/nginx-proxy/ssl:/ssl
    environment:
      - NODE_ENV=staging
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/fefefe/efeefefe/efefefefe
      - SLACK_CHANNEL=foo-status
      - API_MAILGUN_API_KEY=key-1234567890
      - VIRTUAL_HOST=staging.levibostian.com
      - VIRTUAL_LETSENCRYPT=foo-app
      - VIRTUAL_URL=/
    depends_on:
      - nginx-proxy
  nginx-proxy:
    image: "tozd/nginx-proxy"
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - LETSENCRYPT_EMAIL=foo@example.com
      - MAILTO=foo@example.com
      - ADMINADDR=lfoo@example.com
      - 'REMOTES=smtp.mailgun.org smtp --port=587 --starttls --user=postmaster@ops.example.com --pass=1234567890'
    volumes:
      - /etc/docker/nginx-proxy/var/log/letsencrypt:/var/log/letsencrypt
      - /etc/docker/nginx-proxy/var/log/nginx:/var/log/nginx
      - /etc/docker/nginx-proxy/ssl:/ssl
      - /etc/docker/nginx-proxy/var/log/dnsmasq:/var/log/dnsmasq
      - /etc/docker/nginx-proxy/var/log/dockergen:/var/log/dockergen
      - /var/run/docker.sock:/var/run/docker.sock
