version: '2'
services:
  app:
    container_name: app
    mem_limit: 250000000 # Nodejs best practice to limit memory on applications.
    memswap_limit: 500000000
    depends_on:
      - redis
    expose:
      - "5000"
  redis:
    image: "redis:4.0-alpine"
    container_name: app-redis
    expose:
        - "6379"
