apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: app-config
  files:
  - app/config/projects.json
- name: dotenv
  files:
  - .env
generatorOptions:
  disableNameSuffixHash: true