# !!! - These are lines that  you need to edit to align with your project

apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
    - image: ghcr.io/github-username/repo-name # !!!
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync: # This is explained better in DEV.md document. 
        infer:
        - 'dist/**/*.js'
        - 'app/**/*.ts'
        - 'dist/**/*.map'
  local: 
    push: false

deploy:
  helm:
    releases:
    - name: app-release # !!!
      namespace: "app-name-{{.DEPLOY_ENV}}" # !!! only edit `app-name` to your app name
      chartPath: 'charts/'
      setValueTemplates:
        secrets:
          dotenv: "{{.DOTENV}}"
          projects: "{{.PROJECTS}}"
      wait: true
      remote: false
      artifactOverrides:
        image: ghcr.io/github-username/repo-name # !!! Skaffold continuously tags your image, so no need to put one here.

profiles:
- name: ci-deploy
  activation:
    - env: CI=true
  build:
    tagPolicy:
      envTemplate:
        template: "{{.IMAGE_TAG}}"
    artifacts:
      - image: ghcr.io/github-username/repo-name # !!!
        context: .
        docker:
          dockerfile: Dockerfile
          buildArgs:
            ENV: "{{.DEPLOY_ENV}}"

# As long as you pass `--port-forward` to `skaffold dev/debug`, this maps local port 5000 to the node application
portForward:
- resourceType: service
  resourceName: app-service # !!! this value is dynamic from the helm chart. Set value to charts/templates/deployment.yaml service name at bottom of file. 
  port: 80
  localPort: 5000