apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-pdb
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }} 
  # minAvailable: "40%" # 60% of the desired number of replicas must exist as healthy
  selector:
    matchLabels:
      app: {{ .Chart.Name }}