apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret-dotenv
type: Opaque
data:
  .env: {{ .Values.secrets.dotenv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret-projects
type: Opaque
data:
  projects.json: {{ .Values.secrets.projects }}
