debug = false

loglevel = "ERROR" 
defaultEntryPoints = ["https", "http"]

[entryPoints]
   [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
   [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
   [entryPoints.dashboard]
      address = ":8080"
      [entryPoints.dashboard.auth.basic]
      users = ["admin:12345"]

[api]
  entryPoint = "dashboard"

[retry]

[docker]
   endpoint = "unix:///var/run/docker.sock"
   domain = "foo.com"
   network = "external"
   watch = true 
   exposedByDefault = false 

[acme]
   email = "foo@gmail.com"
   storage = "acme.json"   
   # Comment below to switch to prod server instead of staging below
   # caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
   onHostRule = true
   entryPoint = "https"

   [acme.dnsChallenge]
      provider = "cloudflare"
      delayBeforeCheck = 0

   # Specify domain names here, or, because onHostRule is set to true, you can add domains through docker container starting
   # as long as the docker container contains the appropriate docker labels to enable. 
   [[acme.domains]]
      main = "*.foo.com" # must use dns challenger for wildcard domains. 
      sans = ["foo.com"]