- name: Install redis
  apt:
    name: redis-server
- name: Associate Redis with systemd    
  lineinfile:
    path: '{{redis_config_file_location}}'
    regexp: "^(# )?supervised.*"
    line: supervised systemd
  notify: restart redis
- name: Allow connections from Internet
  lineinfile:
    path: '{{redis_config_file_location}}'
    regexp: "^(# )?bind.*"
    line: "# bind"
- name: Rename dangerous commands 
  blockinfile:
    path: '{{redis_config_file_location}}'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - RENAME COMMAND {{item.name}}"
    insertafter: "^# Command renaming.*"
    block: |
      rename-command {{ item.name }} {{ item.value }}
  loop: "{{ redis.rename_commands }}"    
- name: Set password
  lineinfile:
    path: '{{redis_config_file_location}}'
    regexp: "^(# )?requirepass.*"
    line: "requirepass {{redis.password}}"
- name: Restart redis
  service:
    name: redis
    state: restarted  
- name: Assert redis setup
  script: scripts/test_setup.sh {{redis.password}}