version: '2'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=11111
      - POSTGRES_DB=api-prod
  db-backup:
    image: schickling/postgres-backup-s3
    container_name: db-backup
    restart: always
    links:
      - db
    environment:
      - SCHEDULE=@daily
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY_ID=AAAAAAAA
      - S3_SECRET_ACCESS_KEY=83848484484848575855938
      - S3_BUCKET=api-backups
      - S3_PREFIX=subdirectory-name
      - POSTGRES_DATABASE=api-prod
      - POSTGRES_HOST=111.111.111.111
      - POSTGRES_PORT=5432
      - POSTGRES_USER=prod
      - POSTGRES_PASSWORD=passwordhere
      - 'POSTGRES_EXTRA_OPTS=--schema=public --blobs'