name: Testing deployment 
on:
  push:
    branches:
      - main
      - beta 

env:
  DEPLOY_ENV: testing
  MAKE_RELEASE: true
  K8S_NAMESPACE: app-testing
  DOCKER_REGISTRY: ghcr.io # github registry. You need to also edit skaffold config with this. 
  DOCKER_USERNAME: username-here
  CICI_DECRYPT_KEY: ${{ secrets.CICI_DECRYPT_KEY }}
  CICI_DECRYPT_IV: ${{ secrets.CICI_DECRYPT_IV }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPOS_PUSH_GITHUB_TOKEN: ${{ secrets.REPOS_PUSH_GITHUB_TOKEN }} # personal access token where github username has push access to the repo to make comments and releases. 
  HONEY_BADGER_API_KEY: ${{ secrets.HONEY_BADGER_API_KEY }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }} # base64 encoded kube config file to authenticate with k8s cluster with. 

jobs:
  deploy:
    name: Deploy to testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
      - name: Get secrets 
        run: sudo gem install cici && cici decrypt --verbose --set common && cici decrypt --verbose --set $DEPLOY_ENV
      - name: Setup k8s
        run: mkdir -p ~/.kube/ && cat $KUBE_CONFIG | base64 --decode > ~/.kube/config
      - name: Deploy
        run: ./bin/deploy.sh